### ISSUE TITLE
Bug: wordle didn't signal failure after 6 guesses

### ISSUE THREAD

**Issue by MaikoTan** [koishijs/wordle#29]
From #26 , I turns out that wordle should signal a failure after 6 guesses, but it didn't currently.

Looks like the code here is evaluated the former part first causing the error:

https://github.com/koishijs/wordle/blob/1f1ecc6d95ac4ca9cf88c59aef8240f2971e7073/packages/core/src/index.ts#L202

**Comment by TTsdzb** [comment]
The fix of this issue is still not published yet (last publish on npm on 2023.10.29). Please publish a new version since the plugin does not function as it is intended.

**Comment by TTsdzb** [comment]
The fix of this issue haven't published yet (last publish on npm on 2023.10.29). Please publish a new version, since the plugin is not working as it's intended.
